[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

borsh  = "0.9.3"
# num-derive = "0.3"
# num-traits = "0.2"
keri = "0.8.1"
solana-client = "1.9.8"
solana-keri = {path="../program",version="0.1.0"}
solana-sdk = "1.9.8"
solana-transaction-status = "1.9.8"
thiserror = "1.0"

[dev-dependencies]
solana-sdk = "1.9.8"
solana-logger = "1.9.8"
solana-rpc = "1.9.8"
solana-test-validator =  "1.9.8"
